# Generated by Django 3.2.25 on 2024-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_modelvmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVipis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=256, verbose_name='NameDepartmetn')),
                ('values_data', models.PositiveIntegerField(blank=True, null=True, verbose_name='ValuesData')),
                ('name_data', models.CharField(max_length=256, verbose_name='NameData')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Edited')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
